import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { usersService } from '@/services/user.service'
import { GetServerSideProps } from 'next'
import SmartstoreForm from '@/components/engines/SmartstoreForm'
import { useRecoilState } from 'recoil'
import { common } from '@/lib/store/common'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

const Home = ({ data }: { data: any[] }) => {
  const router = useRouter()
  const [commonState, setCommonState] = useRecoilState(common)

  useEffect(() => {
    if (!commonState.isLogin) {
      router.push('/')
    }
  }, [commonState.isLogin, router])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.query.enginesForm === 'smartstore' && <SmartstoreForm />}
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await usersService.getUser()

  return {
    props: {
      data,
    },
  }
}
